module.exports = {
  auditorList: `select * from auditor`,
  customerList: `select * from customer`,
  crList: `select * from contract_review`,
  auditList: `select t1.name_ko, t2.* from customer t1, certification_audit t2 where t1.customer_id = t2.customer_id`,
  auditListByAuditorEmail: `select * from customer where customer.auditor_email = ?`,
  // auditListByCustomer: `select t1.*, t2.* from customer t1, certification_audit t2  where  t1.customer_id = t2.customer_id and t2.customer_id=?`,
  auditListByCustomer: `select * from certification_audit where customer_id=?`,

  crSelectedList: `select t1.name_ko, t1.auditor_name, t2.* from customer t1, contract_review t2 where t1.customer_id=t2.customer_id`,
  auditorInsert: `insert into auditor set ?`,
  customerInsert: `insert into customer set ?`,
  reportS1Insert: `insert into report_s1 set ?`,
  crInsert: `insert into contract_review set ?`,
  certInsert: `insert into certification_audit set ?`,
  auditorImage: `insert into auditor_image set ?`,
  auditorUpdate: `update auditor set ? where auditor_id=?`,
  customerUpdate: `update customer set ? where customer_id=?`,
  auditorDelete: `delete from auditor where auditor_id=?`,
  customerDelete: `delete from customer where customer_id=?`,
  getAuditor: `select * from auditor where auditor_id=?`,
  customerDetail: `select * from customer where customer_id=?`,
  certDetail: `select t1.*, t2. * from customer t1, certification_audit t2 where t1.customer_id= t2.customer_id and t2.audit_id=?`,
  crDetail: `select * from contract_review where customer_id=?`,
  auditorListByCondition: `select * from auditor where lower(auditor_name) like ?`,
  customerListByCondition: `select * from customer where lower(name_ko) like ?`,
  customerListByEmail: `select * from customer where auditor_email = ?`,
  auditListByCondition: `select t1.name_ko, t2.* from customer t1, certification_audit t2  where  t1.customer_id = t2.customer_id and lower(name_ko) like ?`,
  auditCustomerJoin: `select * from certification_audit inner join customer on certification_audit.customer_id = customer.customer_id where lower(name_ko) like ?`,
  activeCustomers: `select * from customer where status_yn='Y'`,
  signUp: `insert into user set ? on duplicate key update ?`,
  getUser: `select * from user where user_email=?`,
  insertCheckValue: `insert into test set ?`,
};
